config/routes.rb
Rails.application.routes.draw do
  root to: "produtos#index"
  get "produtos/busca", to:"produtos#busca", as: :busca_produto
  resources :produtos, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
    def index
       @produtos = Produto.order(:nome :asc).limit(2)
       @produto_com_desconto = Produto.order(:preco).limit(1)
    end

    def create
        produto = params.require(:produto).permit(:nome, :descricao, :preco, :quantidade)
        Produto.create(produto)

        redirect_to route_url
    end

    def destroy
        id = params[:id]
        Produto.destroy(id)

        redirect_to route_url
    end

    def busca
        @nome = params[:nome]
        @produtos = Produto.where("nome like ?", "%#{nome}%")
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Loja</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= nav_bar brand: "Loja", brand_link: route_url do %>

    <%= menu_group do %>
    <%= menu_item "Criar novo produt", new_produto_path %>
    <% end %>

    <%= form_tag busca_produto_path, method: :get, class:"navbar-form navbar-right" do %>
    <div class="form-group">
        <%= text_field_tag :nome, @nome, class:"form-control" %>
        <%= button_to "Buscar", nil, class:"btn btn-default" %>
    </div>
    <% end %>

    <% end %>

    <div class="container">
        <%= yield %>
    </div>
</body>

</html>

app/views/produtos/busca.html.erb
<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Nome</td>
            <td>Descrição</td>
            <td>Preço</td>
            <td>Quantidade</td>
        </tr>
    </thead>
    <tbody>
        <% @produtos.each do |produto| %>
        <tr>
            <td><%= produto.nome %></td>
            <td><%= produto.descricao %></td>
            <td><%= produto.preco %></td>
            <td><%= produto.quantidade %></td>
            <td>
                <%= button_to "Remover", produto, method: :delete, class:"btn btn-danger",
                data: {confirm: "Tem certeza que deseja remover o produto #{produto.nome}?"} %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/produtos/index.html.erb
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">
        Produto
    </h4>
</div>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Nome</td>
            <td>Descrição</td>
            <td>Preço</td>
            <td>Quantidade</td>
        </tr>
    </thead>
    <tbody>
        <% @produtos.each do |produto| %>
        <tr>
            <td><%= produto.nome %></td>
            <td><%= produto.descricao %></td>
            <td><%= produto.preco %></td>
            <td><%= produto.quantidade %></td>
            <td>
                <%= button_to "Remover", produto, method: :delete, class:"btn btn-danger",
                data: {confirm: "Tem certeza que deseja remover o produto #{produto.nome}?"} %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">
        Produto com desconto
    </h4>
</div>

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <td>Nome</td>
            <td>Descrição</td>
            <td>Preço</td>
            <td>Quantidade</td>
        </tr>
    </thead>
    <tbody>
        <% @produto_com_desconto.each do |produto| %>
        <tr>
            <td><%= produto.nome %></td>
            <td><%= produto.descricao %></td>
            <td><%= produto.preco %></td>
            <td><%= produto.quantidade %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/produtos/new.html.erb
<%= form_for Produto.new do |form| %>

<div class="row">
    <div class="col-sm-8">
        <div class="form-group">
            <%= form.label :nome %>
            <%= form.text_field :nome, class:"form-control" %>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-8">
        <div class="form-group">
            <%= form.label :descricao %>
            <%= form.text_area :descricao, class:"form-control", rows:4 %>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-8">
        <div class="form-group">
            <%= form.label :preco %>
            <%= form.text_field :preco, class:"form-control", step:0.01 %>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-sm-8">
        <div class="form-group">
            <%= form.label :quantidade %>
            <%= form.text_field :quantidade, class:"form-control" %>
        </div>
    </div>
</div>

<%= form.submit "Criar", class:"btn btn-primary" %>
<% end %>